### ISSUE TITLE
crash when editing Internet Radio

### ISSUE THREAD

**Issue by nerijus** [gogglesmm/gogglesmm#56]
If I press right mouse button on Internet radio station and choose Edit...:
```
terminate called after throwing an instance of 'FX::FXRangeException'

Thread 1 "gogglesmm" received signal SIGABRT, Aborted.
(gdb) bt
#0  0x00007ffff42786f5 in raise () from /lib64/libc.so.6
#1  0x00007ffff427a2fa in abort () from /lib64/libc.so.6
#2  0x00007ffff4bb73ed in __gnu_cxx::__verbose_terminate_handler() () from /lib64/libstdc++.so.6
#3  0x00007ffff4bb5196 in ?? () from /lib64/libstdc++.so.6
#4  0x00007ffff4bb51e1 in std::terminate() () from /lib64/libstdc++.so.6
#5  0x00007ffff4bb53f9 in __cxa_throw () from /lib64/libstdc++.so.6
#6  0x00007ffff796c592 in FX::FXDictionary::at(char const*) () from /lib64/libFOX-1.7.so.0
#7  0x00000000004a1033 in GMTrackDatabase::listTags(FX::FXComboBox*, bool) ()
#8  0x00000000004bef0e in GMStreamSource::onCmdEditStation(FX::FXObject*, unsigned int, void*) ()
#9  0x00000000004bfaa9 in GMStreamSource::handle(FX::FXObject*, unsigned int, void*) ()
#10 0x00007ffff7a009f3 in FX::FXObject::tryHandle(FX::FXObject*, unsigned int, void*) ()
   from /lib64/libFOX-1.7.so.0
#11 0x00007ffff79fb18c in FX::FXMenuCommand::onButtonRelease(FX::FXObject*, unsigned int, void*) ()
   from /lib64/libFOX-1.7.so.0
#12 0x00000000004cb386 in GMMenuCommand::handle(FX::FXObject*, unsigned int, void*) ()
#13 0x00007ffff7943408 in FX::FXApp::dispatchEvent(_XEvent&) () from /lib64/libFOX-1.7.so.0
#14 0x000000000043897e in GMApp::dispatchEvent(_XEvent&) ()
#15 0x00007ffff79421bc in FX::FXApp::runOneEvent(long) () from /lib64/libFOX-1.7.so.0
#16 0x00007ffff7942682 in FX::FXApp::runPopup(FX::FXWindow*) () from /lib64/libFOX-1.7.so.0
#17 0x00000000004cfe62 in gm_run_popup_menu(FX::FXMenuPane*, int, int) ()
#18 0x00000000004b63dd in GMTrackView::onTrackContextMenu(FX::FXObject*, unsigned int, void*) ()
#19 0x00000000004b358b in GMTrackView::handle(FX::FXObject*, unsigned int, void*) ()
#20 0x00007ffff7a009f3 in FX::FXObject::tryHandle(FX::FXObject*, unsigned int, void*) ()
   from /lib64/libFOX-1.7.so.0
#21 0x00000000004a9d2e in GMTrackList::onRightBtnRelease(FX::FXObject*, unsigned int, void*) ()
#22 0x00000000004ae039 in GMTrackList::handle(FX::FXObject*, unsigned int, void*) ()
#23 0x00007ffff7943080 in FX::FXApp::dispatchEvent(_XEvent&) () from /lib64/libFOX-1.7.so.0
#24 0x000000000043897e in GMApp::dispatchEvent(_XEvent&) ()
#25 0x00007ffff79421bc in FX::FXApp::runOneEvent(long) () from /lib64/libFOX-1.7.so.0
#26 0x00007ffff794222a in FX::FXApp::run() () from /lib64/libFOX-1.7.so.0
#27 0x000000000047215b in GMPlayerManager::run(int&, char**) ()
#28 0x00000000004c7294 in main ()
```

**Comment by gogglesguy** [comment]
Fixed in 1.1.0
